// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zaczy.SongBook.Data;

#nullable disable

namespace Zaczy.SongBook.Migrations
{
    [DbContext(typeof(SongBookDbContext))]
    [Migration("20260124210332_ScrollingColums")]
    partial class ScrollingColums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Zaczy.SongBook.Data.SongEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("artist");

                    b.Property<string>("Capo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("capo");

                    b.Property<string>("ChordsVariations")
                        .HasColumnType("longtext")
                        .HasColumnName("chords_variations")
                        .HasAnnotation("Relational:JsonPropertyName", "chords_variations");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Lyrics")
                        .HasColumnType("longtext")
                        .HasColumnName("lyrics");

                    b.Property<string>("LyricsAuthor")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lyrics_author")
                        .HasAnnotation("Relational:JsonPropertyName", "lyrics_author");

                    b.Property<string>("MusicAuthor")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("music_author")
                        .HasAnnotation("Relational:JsonPropertyName", "music_author");

                    b.Property<int>("ScrollingDelay")
                        .HasColumnType("int")
                        .HasColumnName("scrolling_delay");

                    b.Property<int?>("ScrollingTempo")
                        .HasColumnType("int")
                        .HasColumnName("scrolling_tempo");

                    b.Property<string>("SpotifyLink")
                        .HasColumnType("longtext")
                        .HasColumnName("spotify_link");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Artist");

                    b.HasIndex("Title");

                    b.ToTable("songs");
                });
#pragma warning restore 612, 618
        }
    }
}
