// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zaczy.SongBook.Data;

#nullable disable

namespace Zaczy.SongBook.Migrations
{
    [DbContext(typeof(SongBookDbContext))]
    [Migration("20260208142930_CategoriesPlus")]
    partial class CategoriesPlus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Zaczy.SongBook.Data.SongCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryColor")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("category_color")
                        .HasAnnotation("Relational:JsonPropertyName", "category_color");

                    b.Property<string>("CategoryColorThemed")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("category_color_themed")
                        .HasAnnotation("Relational:JsonPropertyName", "category_color_themed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_selected");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SongsCount")
                        .HasColumnType("int")
                        .HasColumnName("songs_count")
                        .HasAnnotation("Relational:JsonPropertyName", "songs_count");

                    b.Property<string>("SymbolImage")
                        .HasColumnType("longtext")
                        .HasColumnName("symbol_image")
                        .HasAnnotation("Relational:JsonPropertyName", "symbol_image");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("SongCategories");
                });

            modelBuilder.Entity("Zaczy.SongBook.Data.SongEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("artist");

                    b.Property<string>("Capo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("capo");

                    b.Property<string>("CategoryColor")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("category_color")
                        .HasAnnotation("Relational:JsonPropertyName", "category_color");

                    b.Property<string>("ChordsVariations")
                        .HasMaxLength(140)
                        .HasColumnType("varchar(140)")
                        .HasColumnName("chords_variations")
                        .HasAnnotation("Relational:JsonPropertyName", "chords_variations");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Lyrics")
                        .HasColumnType("longtext")
                        .HasColumnName("lyrics");

                    b.Property<string>("LyricsAuthor")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lyrics_author")
                        .HasAnnotation("Relational:JsonPropertyName", "lyrics_author");

                    b.Property<string>("MoreInfo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("more_info")
                        .HasAnnotation("Relational:JsonPropertyName", "more_info");

                    b.Property<string>("MusicAuthor")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("music_author")
                        .HasAnnotation("Relational:JsonPropertyName", "music_author");

                    b.Property<int?>("ScrollingDelay")
                        .HasColumnType("int")
                        .HasColumnName("scrolling_delay")
                        .HasAnnotation("Relational:JsonPropertyName", "scrolling_delay");

                    b.Property<int?>("SongDuration")
                        .HasColumnType("int")
                        .HasColumnName("song_duration")
                        .HasAnnotation("Relational:JsonPropertyName", "song_duration");

                    b.Property<string>("Source")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("source")
                        .HasAnnotation("Relational:JsonPropertyName", "source");

                    b.Property<string>("SpotifyLink")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("spotify_link")
                        .HasAnnotation("Relational:JsonPropertyName", "spotify_link");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Artist");

                    b.HasIndex("Title");

                    b.ToTable("songs");
                });
#pragma warning restore 612, 618
        }
    }
}
